<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-08-17T01:50:34Z" name="Default Suite" finished-at="2023-08-17T01:54:06Z" duration-ms="212267">
    <groups>
    </groups>
    <test started-at="2023-08-17T01:50:34Z" name="WhiteTower" finished-at="2023-08-17T01:54:06Z" duration-ms="212267">
      <class name="TestTodoMVC.MyTestingClass">
        <test-method is-config="true" signature="launchBrowser()[pri:0, instance:TestTodoMVC.MyTestingClass@4d0f2471]" started-at="2023-08-17T01:50:34Z" name="launchBrowser" finished-at="2023-08-17T01:51:45Z" duration-ms="71413" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method signature="testcase1()[pri:0, instance:TestTodoMVC.MyTestingClass@4d0f2471]" started-at="2023-08-17T01:51:45Z" name="testcase1" finished-at="2023-08-17T01:51:45Z" duration-ms="32" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[ToDo 3 is not in third position expected [ToDo 3] but found [ToDo 4]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: ToDo 3 is not in third position expected [ToDo 3] but found [ToDo 4]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at TestTodoMVC.MyTestingClass.testcase1(MyTestingClass.java:93)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testcase1 -->
        <test-method is-config="true" signature="Quit()[pri:0, instance:TestTodoMVC.MyTestingClass@4d0f2471]" started-at="2023-08-17T01:51:45Z" name="Quit" finished-at="2023-08-17T01:51:46Z" duration-ms="230" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Quit -->
        <test-method is-config="true" signature="launchBrowser()[pri:0, instance:TestTodoMVC.MyTestingClass@4d0f2471]" started-at="2023-08-17T01:51:46Z" name="launchBrowser" finished-at="2023-08-17T01:52:25Z" duration-ms="39598" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method signature="testcase2()[pri:0, instance:TestTodoMVC.MyTestingClass@4d0f2471]" started-at="2023-08-17T01:52:25Z" name="testcase2" finished-at="2023-08-17T01:52:29Z" duration-ms="3270" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testcase2 -->
        <test-method is-config="true" signature="Quit()[pri:0, instance:TestTodoMVC.MyTestingClass@4d0f2471]" started-at="2023-08-17T01:52:29Z" name="Quit" finished-at="2023-08-17T01:52:29Z" duration-ms="175" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Quit -->
        <test-method is-config="true" signature="launchBrowser()[pri:0, instance:TestTodoMVC.MyTestingClass@4d0f2471]" started-at="2023-08-17T01:52:29Z" name="launchBrowser" finished-at="2023-08-17T01:54:00Z" duration-ms="91162" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method signature="testcase3()[pri:0, instance:TestTodoMVC.MyTestingClass@4d0f2471]" started-at="2023-08-17T01:54:00Z" name="testcase3" finished-at="2023-08-17T01:54:06Z" duration-ms="6183" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testcase3 -->
        <test-method is-config="true" signature="Quit()[pri:0, instance:TestTodoMVC.MyTestingClass@4d0f2471]" started-at="2023-08-17T01:54:06Z" name="Quit" finished-at="2023-08-17T01:54:06Z" duration-ms="182" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Quit -->
      </class> <!-- TestTodoMVC.MyTestingClass -->
    </test> <!-- WhiteTower -->
  </suite> <!-- Default Suite -->
</testng-results>
